import "../styles/app.css"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  // icon: "./favicon.png",
  title: "Sizwe Mashele | Portfolio",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
          <link rel="icon" href="@/app/favicon.png" />
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </>
  )
}
